### ISSUE TITLE
PinkSale snipe exception

### ISSUE THREAD

**Issue by vaidab** [tsarbuig/Limit-Sniper#3]
Python int too large to convert to C ssize_t
Traceback (most recent call last):
  File "sniper.py", line 5840, in runLoop
    run()
  File "sniper.py", line 5510, in run
    scan_mempool_classic(token)
  File "sniper.py", line 2647, in scan_mempool_classic
    decoded = contract.decode_function_input(input_bytes)
  File "/home/user/.local/lib/python3.8/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/web3/contract.py", line 471, in decode_function_input
    decoded = self.web3.codec.decode_abi(types, cast(HexBytes, params))
  File "/home/user/.local/lib/python3.8/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/home/user/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/user/.local/lib/python3.8/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/user/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/home/user/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/user/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 144, in decode
    stream.push_frame(start_pos)
  File "/home/user/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 95, in push_frame
    self.seek_in_frame(0)
  File "/home/user/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 84, in seek_in_frame
    self.seek(self._total_offset + pos, *args, **kwargs)
OverflowError: Python int too large to convert to C ssize_t

**Comment by tsarbuig** [comment]
hey bro, which version of the bot were you using ?
